---
- name: Installing and starting nginx web server
  hosts: all
  become: yes  # run tasks as sudo

  tasks:
    - name: Update apt package cache
      apt:
        update_cache: yes
        cache_valid_time: 3600  # optional: avoid frequent updates

    - name: Install nginx
      apt:
        name: nginx
        state: present

    - name: Start and enable nginx service
      service:
        name: nginx
        state: started
        enabled: true
